### ISSUE TITLE
Reference frame inconsistency for combined simulations

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#16]
In #5 we agreed to output all maps in Equatorial.
WebSky Sims instead were not rotated and assumed in Equatorial.
This creates an issue, see my note here: https://github.com/simonsobs/map_based_simulations/commit/de26612db99c6c00f502910ee0a4d60290284ced

Same applies for the TOD simulations.
I could hack the TOD simulations script to get a consistent result but looks error prone.
I'd rather run the TOD simulations rotating everything to Equatorial, then create another extragalactic release rotated to Equatorial so that we have consistent sky in TOD Sims and mbs.

Anyone has suggestions or better solution to this?

**Comment by zonca** [comment]
For reference 

* Discussion of sky for TOD some https://github.com/simonsobs/so_pysm_models/issues/32
* Implementation of sky in TOAST pipeline https://github.com/simonsobs/sotodlib/pull/23

**Comment by msyriac** [comment]
I don't think I understand the issue. Even though the isotropy of the sims means it shouldn't matter, what's wrong with continuing to interpret the Websky sims as being in Equatorial coordinates?

**Comment by zonca** [comment]
If we run a combined simulation with PySM, as we do in TOD sims, we either rotate both galactic and WebSky or none.
So we will have WebSky sims inside TOD sims rotated to Equatorial, while mbs are not. So if people compare them they'll find this discrepancy

**Comment by msyriac** [comment]
Ok, that sounds bad. The original websky sims should be assumed to be in Equatorial. They should be rotated only if Galactic coordinates are asked for.

**Comment by zonca** [comment]
Is this just to minimize the rotations because we will mostly be using Equatorial, right?

**Comment by zonca** [comment]
In this case I think I can add functionality in PySM 3 to handle this . In PySM 2 this won't work

**Comment by msyriac** [comment]
Yes, I remember one of the Websky creators asking us to interpret it as in Equatorial coordinates, but I can't find their message now.

**Comment by zonca** [comment]
I got a better plan:
* I already have all SO galactic input templates rotated to Equatorial
* I'll switch so_pysm_model to use those by default
* TOD sims will use all Equatorial with no need to rotate
* If anyone wants galactic they can rotate after running PySM

**Comment by zonca** [comment]
ok,
* `so_pysm_models` starting from version 2.0 defaults to equatorial: https://github.com/simonsobs/so_pysm_models/commit/510792a1a94295c4e3d809656fd136f2ad23a1b3
* see https://github.com/simonsobs/sotodlib/pull/23/files#r298258775 for TOD pipeline setup
