### ISSUE TITLE
Websky CIB simulations at more frequencies

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#17]
@marcelo-alvarez here are the currently available CIB frequencies:

https://portal.nersc.gov/project/cmb/so_pysm_models_data/websky/0.3/

I'm now running with bandpasses (#12), and the lower channel gets down to 21.7GHz. Can you please extend the WebSky CIB until 20 or 21 GHz?

Also, it would be nice to add a few more frequencies also between channels, so that the interpolation is not across a wide frequency range.

**Comment by zonca** [comment]
Here is the latest table of frequencies:

![Screenshot 2019-07-03 at 01 33 47](https://user-images.githubusercontent.com/383090/60553310-fd977d00-9d32-11e9-865f-11bdb3c9424a.png)

**Comment by marcelo-alvarez** [comment]
@zonca -- I am in the process of updating / improving the CIB model in websky to correct a bug in the treatment of satellite galaxies. Would it be acceptable to use this updated model for this?

**Comment by zonca** [comment]
Yes

**Comment by zonca** [comment]
@marcelo-alvarez @msyriac as discussed today at the FG call, it would be nice to have more CIB maps.

## Choose the number of points in frequency

But not too many! The problem is that if PySM is being used for multiple channels, we need to keep these maps in memory as we loop through channels, so impact on memory consumption is high.
PySM does integration with `trapz`, so basically linear interpolation, how does the CIB differ from linear interpolation? if not too much, I would limit just to ~5 maps for each channel, `[low, low-mid, mid, high-mid, high]`, in any case keep them equally spaced in the bandwidth, i.e. I would remove maps too close to the center freq (like 91 GHz and 93 GHz for the 92 GHz channel).

## Choose the frequencies

The table above gives center frequency and bandwidth, it would be nice to have simulations just below and just above the boundary of each frequency channel, e.g. 92 GHz, bandwidth is 26 GHz, so lower boundary is 79 GHz, maybe we do 10% of the bandwidth lower, like 76 GHz?

**Comment by msyriac** [comment]
Perhaps we can do a test where we bandpass integrate ~545 GHz and/or ~353 GHz websky cib maps with the Planck bandpass for a few versus a dozen and compare the final maps.

**Comment by marcelo-alvarez** [comment]
@msyriac would it be useful to generate and update to the table above to contain all the frequencies we need (i.e. including ACT, Planck, ..)? then I could run the 5 maps per channel as @zonca suggested.

**Comment by marcelo-alvarez** [comment]
@zonca wrote:
> PySM does integration with `trapz`, so basically linear interpolation, how does the CIB differ from linear interpolation? 
we have not investigated this in detail. it's also not clear exactly what statistic to use for answering 'how does the CIB differ from linear interpolation?' qualitatively. @msyriac @jcolinhill any thoughts on this?

**Comment by jcolinhill** [comment]
I agree with Mat's suggestion of comparing a 5-map interpolation to a >>5 map interpolation.  We could just look at difference maps afterward, and see how large any residuals are.  Also power spectra etc

**Comment by zonca** [comment]
@marcelo-alvarez would you have any update on this?

**Comment by marcelo-alvarez** [comment]
We have now validated the revised CIB model and are in the process of generating CIB maps at a range of frequencies near 353 and 545. @msyriac, what frequency range should I sample in for these two?

**Comment by marcelo-alvarez** [comment]
In the meantime we will sample with 5 maps per frequency band in the table above.

**Comment by marcelo-alvarez** [comment]
@zonca are the following frequencies acceptable? Values and plot were generated by @msyriac 

[21.6, 24.47, 27.33, 30, 35.93, 41.67, 44, 47.4, 63.9, 67.8, 70, 73.7, 79.6, 90.16, 100, 111.49, 128.99, 143, 152.65, 164.48, 188.56, 210.29, 217, 232.03, 256.0, 275.17, 294.33, 305.84, 313.5, 340.21, 353, 374.59, 408.96, 466.56, 525.36, 545, 584.17, 642.97, 728.93, 817.39, 857, 905.86, 994.32]

![2019-10-02_16_13_14](https://user-images.githubusercontent.com/32470484/66521335-ceb24500-ea9f-11e9-82b8-cec8df58752b.png)

**Comment by zonca** [comment]
Can we add one point above and one below at about the same spacing? Also what about rounding to nearest integer frequency?

**Comment by marcelo-alvarez** [comment]
I added one above and one below, and rounded to 3 significant digits:

[18.7, 21.6, 24.5, 27.3, 30.0, 35.9, 41.7, 44.0, 47.4, 63.9, 67.8, 70.0, 73.7, 79.6, 90.2, 100, 111, 129, 143, 153, 164, 189, 210, 217, 232, 256, 275, 294, 306, 314, 340, 353, 375, 409, 467, 525, 545, 584, 643, 729, 817, 857, 906, 994, 1080]

**Comment by zonca** [comment]
It would be interesting to plot this: how many points would a 20% and a 30% bandwidth require to read as a function of frequency?

**Comment by marcelo-alvarez** [comment]
It looks like it should always be less than about five, by construction, since 
@msyriac chose 5 channels per band.

**Comment by zonca** [comment]
Ok, I'll cross-check that but you can go ahead and produce them at 8192

**Comment by zonca** [comment]
@marcelo-alvarez any news about this? do we have the 8192 maps at the frequencies above?

**Comment by marcelo-alvarez** [comment]
We don't yet have these CIB + Radio maps, @xzackli can you produce these with your xgpaint version? I will produce kSZ and tSZ with the latest websky.

**Comment by xzackli** [comment]
Back from vacation, I'll produce these maps.

**Comment by zonca** [comment]
@xzackli @marcelo-alvarez do you have the maps at nside 8192? are they available at NERSC?

**Comment by xzackli** [comment]
I'll move them to NERSC and send you the directory this weekend, they've been sitting on tigress.

**Comment by zonca** [comment]
@xzackli do you have any update on this?

**Comment by xzackli** [comment]
I found it really annoying to `rsync` the files over, so instead I ran my code on the NERSC cluster. Cori has slow IO, so I don't know if I really saved time. The maps are in, and all groups have `r` permissions.

```
/global/cscratch1/sd/xzackli/cib/share
```

**Comment by zonca** [comment]
@xzackli I get permission denied

**Comment by zonca** [comment]
@xzackli I still get permission denied, you should make your scratch folder readable and executable by the `simonsobs` group:

```
ls -ld /global/cscratch1/sd/xzackli/
drwx------ 9 xzackli xzackli 12288 Feb 21 05:14 /global/cscratch1/sd/xzackli/
```

**Comment by xzackli** [comment]
This is terribly embarrassing for me, I must have set the wrong string of numbers. I've applied 777 for now, and I'll look into how to set the right permissions.

**Comment by zonca** [comment]
no worries, unix permissions are an ancient awkward thing.

you need to fix permissions also for the root folder:

```
ls -ld /global/cscratch1/sd/xzackli/
drwx------ 9 xzackli xzackli 12288 Feb 21 05:14 /global/cscratch1/sd/xzackli/
```

**Comment by xzackli** [comment]
Done! 

```
ls -ld /global/cscratch1/sd/xzackli/
drwxrwxrwx 9 xzackli xzackli 12288 Feb 21 05:14 /global/cscratch1/sd/xzackli/
```

**Comment by zonca** [comment]
ls -ld /gl
obal/cscratch1/sd/xzackli/cib
drwxrwx--- 3 xzackli xzackli 4096 Feb 19 09:39
/global/cscratch1/sd/xzackli/cib

**Comment by xzackli** [comment]
Ok, I've set the permissions on every parent directory.

```
ls -ld /global/cscratch1/sd/xzackli/
drwxrwxrwx 9 xzackli xzackli 12288 Feb 21 05:14 /global/cscratch1/sd/xzackli/
ls -ld /global/cscratch1/sd/xzackli/cib
drwxrwxrwx 3 xzackli xzackli 4096 Feb 19 09:39 /global/cscratch1/sd/xzackli/cib
ls -ld /global/cscratch1/sd/xzackli/cib/share
drwxrwxrwx 2 xzackli xzackli 4096 Feb 19 09:29 /global/cscratch1/sd/xzackli/cib/share
ls -ld /global/cscratch1/sd/xzackli/cib/share/cib_100.fits
-rwxrwxrwx 1 xzackli xzackli 3221233920 Feb 19 08:50 /global/cscratch1/sd/xzackli/cib/share/cib_100.fits
```

**Comment by xzackli** [comment]
This discussion has reminded me that I was going to adjust the amplitude of the maps to match Planck (i.e. multiplying every map by some number). What's the path for updating these data products?

**Comment by xzackli** [comment]
@mhasself just taught me how to use Linux permissions, and I've set the `cib` directory to the `sobs` group.

**Comment by zonca** [comment]
ok, got the files, thanks
