### ISSUE TITLE
Increase resolution for next runs

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#18]
I plan to switch to nside 1024 for SAT and 8192 for LAT in the next future, as that agrees with the data interface document.

Just keeping track of this for now, let's discuss in August/September

**Comment by zonca** [comment]
from f2f, no need for 1024 for SAT, keep 512

**Comment by zonca** [comment]
@msyriac can you post here a proposal of a varying NSIDE/resolution for each channel/telescope?

**Comment by msyriac** [comment]
This is my recommendation for the nside (right) based on the FWHM arcmin (left)  
```
SAT
91.0	 128
63.0	 128
30.0	 256
17.0	 512
11.0	 1024
9.0	 1024
LAT
7.4	 1024
5.1	 2048
2.2	 4096
1.4	 8192
1.0	 8192
0.9	 8192
```

Pinging @mhasself @damonge @jcolinhill @dpole @thibautlouis

**Comment by zonca** [comment]
thanks @msyriac can you please also add CAR maps resolution?

**Comment by jcolinhill** [comment]
overall looks good, but I would prefer if the LAT 30 GHz channel (7.4 arcmin FWHM) is at Nside=2048.  Planck 143 GHz is at roughly the same resolution, and they use Nside=2048.

**Comment by msyriac** [comment]
Updated recommendation including CAR pixel size in arcmin, and incorporating Colin's request:
```
91.0	 128 	 32.00
63.0	 128 	 32.00
30.0	 256 	 15.00
17.0	 512 	 8.00
11.0	 1024 	 4.50
9.0	 1024 	 4.50
7.4	 2048 	 2.00
5.1	 2048 	 2.00
2.2	 4096 	 0.50
1.4	 8192 	 0.50
1.0	 8192 	 0.50
0.9	 8192 	 0.50
```

@amaurea should probably look at this too!

**Comment by mhasself** [comment]
Wouldn't it be easier if the CAR resolutions scale by powers of 2, tied to NSIDE?  I.e. insist that:

   CDELT = C / NSIDE

Mat's suggestion is close to C = 64 degrees... resolutions would be (30,15,7.5, ..., 0.46875) arcminutes.  If you prefer (32,16,8,...,0.5), set C = (1048 deg/15).

**Comment by msyriac** [comment]
Since the CAR maps will likely be used by source/object/cluster people, I would prefer to have the LAT high frequencies to have identical pixelization (as we do in ACT currently), at the cost of oversampling a bit at low freq and undersampling a bit at high freq. That said, powers of two are good, so here's an update:

```
91.0	 128 	 32.00
63.0	 128 	 32.00
30.0	 256 	 16.00
17.0	 512 	 8.00
11.0	 1024 	 4.00
9.0	 1024 	 4.00
7.4	 2048 	 2.00
5.1	 2048 	 2.00
2.2	 4096 	 0.50
1.4	 8192 	 0.50
1.0	 8192 	 0.50
0.9	 8192 	 0.50
```

**Comment by mattyowl** [comment]
Yeah - for cluster stuff it makes life a lot easier if all the maps have the same pixelisation. I think we need NSIDE=8192.

**Comment by zonca** [comment]
thanks @mattyowl, would you like nside 8192 also for the channel at 2.2 arcmin?

**Comment by mattyowl** [comment]
Yes please, I think so

**Comment by msyriac** [comment]
Updating based on Matt's suggestion:

```
fwhm     NSIDE  CAR resol
91.0	 128 	 32.00
63.0	 128 	 32.00
30.0	 256 	 16.00
17.0	 512 	 8.00
11.0	 1024 	 4.00
9.0	 1024 	 4.00
7.4	 2048 	 2.00
5.1	 2048 	 2.00
2.2	 8192 	 0.50
1.4	 8192 	 0.50
1.0	 8192 	 0.50
0.9	 8192 	 0.50
```

**Comment by zonca** [comment]
Thanks @mattyowl and @msyriac, I think we should also think about `ell_max` for the harmonic expansions, (used both for reprojections, see #13, or beam smoothing), what about `3*nside-1` for `nside<8192` and `2*nside` for `nside=8192`? Or are we interested in `ell>16384`?

**Comment by aiolasimone** [comment]
It becomes a bit tricky with localized features, such as point sources or dust clumps close to the galaxy.
We should check that `16384` is enough to make ringing around point sources negligible compared to the noise level.
Map-space operations like source and cluster finding, staking, and such may care a lot about this.

**Comment by zonca** [comment]
@aiolasimone who can I ask about operations on point sources?

**Comment by msyriac** [comment]
Let's keep it at 3*nside-1 throughout if possible?

**Comment by msyriac** [comment]
@amaurea  and I chatted about additionally requiring that the CAR maps have integer number of pixels in both directions, and having the different maps be convertible between different pixelizations through integer multiples. We came up with the following, which oversamples the SATs a bit further:

```
tel_freq	fwhm	NSIDE	CAR resol
sat_027     	91.0	128     12.00
sat_039	      	63.0	128     12.00
sat_093   	30.0	256     12.00
sat_145   	17.0	512     4.00
sat_225   	11.0	1024    4.00
sat_280      	9.0	1024    4.00
lat_027      	7.4	2048    2.00
lat_039      	5.1	2048    2.00
lat_093      	2.2	8192    0.50
lat_145      	1.4	8192    0.50
lat_225      	1.0	8192    0.50
lat_280      	0.9	8192    0.50
```

@mhasself

**Comment by zonca** [comment]
@msyriac what if we increase resolution on 93GHz to the same of 145GHz? so that when they are simulated in a dichroic tube they have the same nside.

```
tel_freq	fwhm	NSIDE	CAR resol
sat_027     	91.0	128     12.00
sat_039	      	63.0	128     12.00
sat_093   	30.0	512     4.00
sat_145   	17.0	512     4.00
sat_225   	11.0	1024    4.00
sat_280      	9.0	1024    4.00
lat_027      	7.4	2048    2.00
lat_039      	5.1	2048    2.00
lat_093      	2.2	8192    0.50
lat_145      	1.4	8192    0.50
lat_225      	1.0	8192    0.50
lat_280      	0.9	8192    0.50
```

**Comment by msyriac** [comment]
Yes, that makes sense. Let's go with that.

**Comment by zonca** [comment]
ok,
this is implemented in `mapsims` and is the default is `nside` is set to None,
see https://github.com/simonsobs/mapsims/blob/master/mapsims/data/so_default_resolution.csv

First release using this is https://github.com/simonsobs/map_based_simulations/tree/master/202002_noise

Next also a foreground simulation natively at these NSIDEs
