### ISSUE TITLE
Plan new noise simulations

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#21]
* Implement new noise model from: https://github.com/simonsobs/V3_calc/blob/master/so_noise_lat_v3_1_CAND.py
* New hitmaps, from TOD simulations?
* Frequency channel correlations?

**Comment by zonca** [comment]
@keskitalo do we have hitmaps from MSS-0001 we can use?

**Comment by keskitalo** [comment]
@zonca the simulation is only 20% complete but the hitmaps for the subsets are designed to be very similar. All of the results are being written here: `/global/cscratch1/sd/keskital/pwg-scripts/pwg-tds/mss-0001/genesis/out/00000000`. Hit maps are the files that end with `_hmap.fits`.

**Comment by zonca** [comment]
get the new noise model: https://github.com/simonsobs/V3_calc/issues/2#issuecomment-536060305

**Comment by zonca** [comment]
the available hitmaps are:

```
LT0_UHF1_01_of_20.nominal_telescope_all_time_all_hmap.fits  LT5_MFS2_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT0_UHF2_01_of_20.nominal_telescope_all_time_all_hmap.fits  LT6_LF1_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT1_UHF1_01_of_20.nominal_telescope_all_time_all_hmap.fits  LT6_LF2_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT1_UHF2_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST0_UHF1_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT2_MFF1_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST0_UHF2_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT2_MFF2_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST1_MFF1_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT3_MFF1_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST1_MFF2_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT3_MFF2_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST2_MFS1_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT4_MFS1_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST2_MFS2_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT4_MFS2_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST3_LF1_01_of_20.nominal_telescope_all_time_all_hmap.fits
LT5_MFS1_01_of_20.nominal_telescope_all_time_all_hmap.fits  ST3_LF2_01_of_20.nominal_telescope_all_time_all_hmap.fits
```

Tubes have slightly different scanning:

![image](https://user-images.githubusercontent.com/383090/70287868-4c838b80-1785-11ea-9dd5-ed6fa8a91b13.png)
![image](https://user-images.githubusercontent.com/383090/70287874-586f4d80-1785-11ea-8c02-aecbcc736a76.png)
![image](https://user-images.githubusercontent.com/383090/70287885-61601f00-1785-11ea-8f22-587fdb373df9.png)

@keskitalo I plan to simulate them separately, which increases the number of maps from 16 to 22 for each noise realization, but it makes it easier to compare with the time domain simulations. Do you agree?

**Comment by zonca** [comment]
## New noise spectra

![image](https://user-images.githubusercontent.com/383090/70289446-a5552300-1789-11ea-8057-4d55dde3f280.png)
![image](https://user-images.githubusercontent.com/383090/70289453-a8e8aa00-1789-11ea-9dd6-7ac1a3b5a953.png)

**Comment by zonca** [comment]
discussing noise splits at https://github.com/simonsobs/map_based_simulations/issues/30

**Comment by zonca** [comment]
about the disk space required to store the simulations with variable NSIDE (#18) and simulating separately the different tubes as the TOD simulations do. I get:

* 120 GB / realization for LAT (14 maps)
* .4 GB / realization for SAT (8 maps)

**Comment by zonca** [comment]
Implementing noise correlations, see as example cross-corralation between the lowest frequency channels, 
[Full notebook](https://gist.github.com/0b91602bb651f251c21064d151999ece)

![image](https://user-images.githubusercontent.com/383090/73481959-aea9d880-4351-11ea-97c1-8f49d97e9ddb.png)

**Comment by zonca** [comment]
Ok,
the HEALPix version of the release is ready, CAR will follow:

https://github.com/simonsobs/map_based_simulations/blob/master/202002_noise

@mhasself can you pelase crosscheck the noise parameters in https://github.com/simonsobs/map_based_simulations/blob/master/202002_noise/noise.toml? in particular `rolloff_ell`.

**Comment by zonca** [comment]
@mhasself do you think `rolloff_ell=50` is fine?

**Comment by mhasself** [comment]
Yes, I think ell=50 is acceptable.

Apologies for the slow reply.

**Comment by zonca** [comment]
thanks!
