### ISSUE TITLE
Bandpass integrated simulations for galactic models with variable spectral index

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#22]
@NicolettaK should I run tophat bandpass simulations also for the `SO_?1` models?

**Comment by NicolettaK** [comment]
We need to do that at some point. Do you want to wait for a feedback from the AWGs?

**Comment by zonca** [comment]
Ok, yes let's wait, there was a lot of code development for these sims, we might find some issues.

**Comment by zonca** [comment]
@NicolettaK next I'll be preparing a new set of foreground simulations, should we use the `_0` or `_1` model? or both?

**Comment by zonca** [comment]
@NicolettaK any feedback about this?

**Comment by NicolettaK** [comment]
@zonca, Sorry I missed this! If you can do it for both. If it is too expensive then I would go with variable spectral indices.

**Comment by zonca** [comment]
will do variable spectral index, see https://github.com/simonsobs/map_based_simulations/issues/32
