### ISSUE TITLE
Do we need CO simulations?

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#23]
The CO component is available in `so_pysm_models`, see [the documentation](https://so-pysm-models.readthedocs.io/en/latest/models.html#colines), it has been implemented by @giuspugl.

We need to check more realistic bandpasses and see if we really need to add CO to our simulations. @giuspugl would you volunteer to do this?

**Comment by giuspugl** [comment]
sure can do that .

**Comment by zonca** [comment]
@giuspugl would you have any update on this?

**Comment by zonca** [comment]
@giuspugl we have some realistic bandpasses, but @smsimon suggested to wait for updated release of this in September. Let's wait for that. Unless someone requests urgently CO maps, then we can do a preliminary release with what is available now.

**Comment by msyriac** [comment]
Sara Simon @smsimon has alerted me to existence of updated bandpass models here: https://github.com/smsimon/bandpasses/ . She tells me these will be incorporated in to sotodlib, but one could fetch them from there and use them right away.

**Comment by zonca** [comment]
@msyriac @giuspugl  I don't see that repo, is it private?

**Comment by msyriac** [comment]
Yes, it's private. I'll ask Sara to make a team or add us to an existing team that gives us access.

**Comment by smsimon** [comment]
@zonca it is here now: https://github.com/simonsobs/instrument_model. We decided to make a general place where instrument modeling things can go and people/sotodlib can access them.

**Comment by zonca** [comment]
@giuspugl would you like to check which CO lines impact which channel using those bandpasses?

**Comment by giuspugl** [comment]
@smsimon for CO studies shall I consider the Bandpassess without any beam effect. Is that ok  ?

**Comment by zonca** [comment]
@smsimon @giuspugl any update on this?

**Comment by giuspugl** [comment]
Yes, working on that.

**Comment by giuspugl** [comment]
### CO lines with realistic bandpasses 

State of the art bandpasses to date can be found in the [instrument model repo](https://github.com/simonsobs/instrument_model), as pointed out by @smsimon. 
#### LAT  
I considered bandpasses from the files [MF_wOMT_wLPF_v1_LAT_beam.txt](https://github.com/simonsobs/instrument_model/blob/master/instrument_hardware/modeled_bandpasses/MF/MF_wOMT_wLPF_v1_LAT_beam.txt)  and [UHF_wOMT_LAT_beam.txt](https://github.com/simonsobs/instrument_model/blob/master/instrument_hardware/modeled_bandpasses/UHF/UHF_wOMT_LAT_beam.txt)
![image](https://user-images.githubusercontent.com/8957029/70971366-a7569600-2055-11ea-9b3b-cccfff5e6a6a.png)


#### SAT  
I considered bandpasses from the files [MF_wOMT_wLPF_v1_SAT_beam.txt](https://github.com/simonsobs/instrument_model/blob/master/instrument_hardware/modeled_bandpasses/MF/MF_wOMT_wLPF_v1_SAT_beam.txt)  and [UHF_wOMT_SAT_beam.txt](https://github.com/simonsobs/instrument_model/blob/master/instrument_hardware/modeled_bandpasses/UHF/UHF_wOMT_SAT_beam.txt)

![image](https://user-images.githubusercontent.com/8957029/70971380-ae7da400-2055-11ea-9ba1-1829cf94ed12.png)

### Summary 
- Bandpasses for  MF are designed in such a way that the CO 1-0 rotational line  is pretty much avoided (transmission at the line frequency, i.e. 115.3 GHz is  1e-4  and 1e-3  respectively for LAT and SAT channels. This also the case for CO3-2 line (at 345.8 GHz) whose transmission is at around 1e-3 for both LAT and SAT
- Conversely, the CO2-1  line  is essentially  transmitted   80 % in the 220 GHz channel for both LAT and SAT.
- We therefore should include CO2-1 emission in our map based simulations

**Comment by zonca** [comment]
in the plan for #39
