### ISSUE TITLE
Noise simulations directly in CAR

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#28]
For noise, can someone volunteer to make a pull request to https://github.com/simonsobs/mapsims/blob/master/mapsims/noise.py to generate noise in CAR? I'll then run the sims. You need to install pysm 3 from github.com/healpy/pysm (clone master and `pip install .` it)

_Originally posted by @zonca in https://github.com/simonsobs/map_based_simulations/issues/13#issuecomment-503068349_

**Comment by zonca** [comment]
basically replace `synalm` at https://github.com/simonsobs/mapsims/blob/master/mapsims/noise.py#L200 to the equivalent in `pixell`

**Comment by msyriac** [comment]
I'm working on this. Is it alright if I do this in the same PR as the splits issue #30 ?

**Comment by zonca** [comment]
Yes, thanks

**Comment by msyriac** [comment]
For the hitmaps, I would like to provide a set of CAR templates at pre-defined resolutions (corresponding to those decided in #18 ). Since the resolution prescriptions might change in the future and since the hitmaps are not final either, I don't think it's a good idea to keep this in the git tree. Do you have a recommendation for a way to store and download these hitmaps as needed?

**Comment by zonca** [comment]
Yes, let's keep them in a dedicated repo using git lfs, then have them
checked out in /project www and served via http. Like so_pysm_models
templates

**Comment by msyriac** [comment]
I couldn't find this done in so_pysm_models. Could you point me to it?

**Comment by zonca** [comment]
https://github.com/simonsobs/so_pysm_models/blob/master/so_pysm_models/utils/__init__.py

**Comment by msyriac** [comment]
@zonca @tskisner @mhasself  I get "Permission denied" when I try to make an so_mapsims_data at:
nersc:/project/projectdirs/cmb/www
@mhasself would it be worth setting up ACL here as well?

**Comment by tskisner** [comment]
Just a reminder that the NERSC project filesystem is being transitioned to a newer and faster "community filesystem".  /project will be made read-only starting at 7am Tuesday, Jan. 14 (during the maintenance window).  See details here:

https://www.nersc.gov/REST/announcements/message_text.php?id=4287

The new filesystem will be online several days later with all the data synced.

**Comment by msyriac** [comment]
Thanks. Now I get "Permission denied" in /global/cfs/cdirs/cmb/www . @mhasself @zonca 
I'm going to temporarily set up shop in /global/cfs/cdirs/sobs/www/users/msyriac/so_mapsims_data .

**Comment by mhasself** [comment]
@msyriac You're not in the "cmb" group / project.  And neither am I.  Isn't "sobs" is the right place for this?

**Comment by zonca** [comment]
thanks @mhasself , 
@msyriac I copied your files to `/global/cfs/cdirs/sobs/www/so_mapsims_data`, I preserved the permissions, but better if you crosscheck.

**Comment by msyriac** [comment]
Looks good; updated the mapsims data urls.
