### ISSUE TITLE
Produce degraded maps for Gaussian simulations

### ISSUE THREAD

**Issue by NicolettaK** [simonsobs/map_based_simulations#3]
I think it would be useful to save the 10 Gaussian realizations produced for the LAT instrument also at the SAT resolution, in order to have maps with the same foreground realization for the two instruments. 
This imply the application of a simple degrade function (with `hp.ud_grade` to go from Nside=4096 to Nside=512) to both the dust and synchrotron maps. 
@zonca could you do that?

**Comment by zonca** [comment]
this refers to the simulation https://github.com/simonsobs/map_based_simulations/tree/master/201901_gaussian_fg_lensed_cmb_realistic_noise

**Comment by NicolettaK** [comment]
It was just to have them ready for everyone. But I agree it is simple for users to do the `ud_grade` if need.

**Comment by zonca** [comment]
thinking better about this, one option would be to avoid using `ud_grade` at all as it can add artifacts to a map and produce LAT simulations natively at 512.
I could take the first 10 realizations at 512 and rerun them adding also LAT channels.
Would anyone be interested in those?

**Comment by zonca** [comment]
no feedback, I'll reopen if anyone asks for them
