### ISSUE TITLE
Differences in the output maps between Planck and SO simulations

### ISSUE THREAD

**Issue by dpole** [simonsobs/map_based_simulations#34]
Hi, just wanted to point out that there seems to be some inconsistencies in the maps provided between the Planck delta-bandpass simulations and the SO tophat runs.

* Planck 545 and 857 GHz maps also have polarization
* Non-polarized foregrounds in one case have polarization equal to zero, in the other polarization is missing

Nothing crucial but maybe it is useful to keep it in mind for future runs as it requires some error-prone exception handling on the user side.

**Comment by zonca** [comment]
yes, that is due to improvements in `mapsims`. New runs should all be consistent.

About Planck polarization, I need to setup a way to handle temperature only maps, will do next time I run Planck.
