### ISSUE TITLE
Decide on coordinate system for maps

### ISSUE THREAD

**Issue by msyriac** [simonsobs/map_based_simulations#5]
The last run of map-based sims had an inconsistency where the Galactic foregrounds were in Galactic coordinates, but the noise sims were in Equatorial coordinates: https://github.com/simonsobs/so_pysm_models/issues/35 (The coordinates of the other components do not matter because the extragalactic universe is isotropic)

Let's use this issue to decide what coordinates our map-based simulations will be in (and by extension, possibly also decide for all SO maps from data and from time-domain sims). The decision here should be documented in the analysis_interface document in https://github.com/simonsobs/tod2maps_docs .

Some things to note:
1. ACT currently produces maps in Equatorial coordinates
2. Planck maps and PySM templates have been produced in Galactic coordinates
3. Reprojection from one coordinate system to the other is possible, but does not preserve every property of the map (i.e. additional characterization may be needed if a map containing data is reprojected, depending on the level of precision and scales used)
4. Instrument/atmospheric noise, ground pickup and other systematics for a ground-based experiment arguably live naturally in Equatorial coordinates.

Due to point 4, my vote is for Equatorial coordinates since operations like local Fourier space filtering are much more natural in this coordinate system. Point 3 does not affect Planck maps and PySM templates because the scales affected by reprojection are scales that are either low S/N (in the data) or are uncertain (in the simulations).

**Comment by keskitalo** [comment]
Since changing coordinate systems is not lossless, it seems best to output in the system that best serves scientific analysis. It is easy enough to rotate maps for visualizing systematics. Large and multi patch analysis would likely lean towards galactic coordinates.

**Comment by mattyowl** [comment]
I think it should be equatorial coordinates. I can't think of a good 
reason why you'd produce the real maps in anything else. Certainly for 
clusters / sources that's the natural system to use.

Cheers
Matt

**Comment by ajvanengelen** [comment]
I vote for Equatorial, for lots of reasons (including ground pick-up) plus it's the traditional system for astronomy at just about every wavelength.

**Comment by msyriac** [comment]
Given the responses here and on #general on the SO slack, can we close this in favor of Equatorial? @zonca

**Comment by zonca** [comment]
Yes, Can you please paste the most important comment from slack here and close the issue?

**Comment by msyriac** [comment]
Since the slack users probably expected privacy, I will not include their usernames:
P1: "there are certain instrumental systematics and noise problems that will show up more cleanly in equatorial coordinates, because the motion of the sky is in right ascension" (with 4 "likes", including mine and from P2)
P2: "I couldn’t agree more with P1, ground pick up is a simple example of systematic that has a simple representation in RA,DEC but might become more difficult in galactic coordinate."
