### ISSUE TITLE
Include inverse noise variance map with simulation output

### ISSUE THREAD

**Issue by msyriac** [simonsobs/map_based_simulations#7]
We should provide either an inverse variance map or a hit count map for each frequency as an output for the map-based simulations (both through the API and as a product saved to disk).

**Comment by zonca** [comment]
yes, we have the white noise level computed here:

https://github.com/simonsobs/mapsims/blob/master/mapsims/SO_Noise_Calculator_Public_20180822.py#L119

and we have the relative hitmap:

https://github.com/simonsobs/mapsims/blob/master/mapsims/noise.py#L109

can you please figure out the right math to get to a inverse variance map? you can either make a pull request or describe the algorithm here and I'll code it.

**Comment by zonca** [comment]
@thibautlouis see relative hitmaps at https://github.com/simonsobs/map_based_simulations/tree/master/201906_noise_no_lowell
