### ISSUE TITLE
Add available galactic masks

### ISSUE THREAD

**Issue by zonca** [simonsobs/map_based_simulations#9]
* [x] @zonca copy masks from scratch to:     /project/projectdirs/sobs/v4_sims/mbs/201904_highres_foregrounds_equatorial/{output_nside}/masks
* [x] @NicolettaK add documentation about masks (how they were generated) in https://github.com/simonsobs/map_based_simulations/blob/master/201904_highres_foregrounds_equatorial/README.md#available-galactic-masks (we can then link to here from other releases)

**Comment by NicolettaK** [comment]
Done in https://github.com/simonsobs/map_based_simulations/pull/10

**Comment by NicolettaK** [comment]
@zonca please copy the masks available here:
/global/cscratch1/sd/krach/SObs/FGawg/masks/270519

**Comment by zonca** [comment]
ok, copied them
